name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy-via-scp
      uses: horochx/deploy-via-scp@master
      with:
        local: ./*
        remote: db94/
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
